# render.yaml (à la racine du repo)
# url seveur :  https://j3d-zoo-escape.onrender.com
# serveur id :  srv-d5ob4htactks73918sog
services:
  - type: web
    name: zoo-escape-server
    env: python
    region: frankfurt  # Proche de la France
    buildCommand: pip install -r requirements.txt
    startCommand: python server/server.py
    envVars:
      - key: PORT
        value: 5555